In [1]:
from numpy import load

data = load('C:/Users/woshi/Desktop/CE_675_Project/Data/short_data/1.npz')
lst = data.files
len(data['NO'])
for item in lst:
    print(item)
    print(data[item])

NO
[[[0.00678392 0.00306165 0.00399017 ... 0.0056853  0.00212498 0.05959651]
  [0.00194775 0.00260152 0.04942476 ... 0.00687575 0.00062855 0.0189943 ]
  [0.00266983 0.0150554  0.01862771 ... 0.00449673 0.00059967 0.02130214]
  ...
  [0.01926336 0.00757765 0.00503778 ... 0.07854629 0.0030808  0.00436385]
  [0.00732548 0.01408814 0.00693663 ... 0.13812889 0.1757867  0.00596037]
  [0.00107522 0.00096894 0.00128575 ... 0.00214413 0.00617047 0.00084447]]

 [[0.00602    0.0027705  0.00356004 ... 0.00480419 0.00190617 0.04924909]
  [0.00171343 0.00237606 0.04257324 ... 0.00562886 0.000576   0.01446241]
  [0.0024031  0.01289358 0.01610956 ... 0.00366909 0.00054308 0.01662086]
  ...
  [0.01607555 0.00689921 0.00490642 ... 0.06897986 0.00284767 0.00401607]
  [0.00645212 0.01177992 0.00600295 ... 0.10973229 0.13894624 0.00492764]
  [0.00102317 0.0009353  0.00123303 ... 0.00201527 0.00609523 0.00078894]]

 [[0.00448505 0.00236431 0.0031298  ... 0.00387634 0.00145983 0.03685259]
  [0.00146479 0.002